name: AI News Crawler

on:
  # 스케줄: 월/수/금 오전 9시, 오후 6시 (UTC 기준이므로 한국시간 -9시간)
  schedule:
    - cron: '0 0,9 * * 1,3,5'  # 월/수/금 오전 9시, 오후 6시 (한국시간)
  
  # 수동 실행 가능
  workflow_dispatch:
  
  # Push할 때도 테스트용으로 실행
  push:
    branches: [ main, master ]
    paths: [ 'crawler/**' ]

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
    
    - name: Python 3.10 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r crawler/requirements.txt
    
    - name: AI 뉴스 크롤링 실행
      env:
        FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}
      run: |
        cd crawler
        python main.py
    
    - name: 크롤링 결과 로그
      if: always()
      run: |
        echo "크롤링 작업 완료"
        echo "실행 시간: $(date)"